---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CLUSTERNAME
  region: REGION

identityProviders:
  - name: PROVIDERNAME
    type: oidc
    issuerUrl: ISSUERURL
    clientId: USERPOOLCLIENTID
    #usernameClaim: email
    #usernamePrefix:
    groupsClaim: "cognito:groups"
    groupsPrefix: "gid:"
    #requiredClaims:
    #  string: string
    #tags:
    #  env: dev
